### ISSUE TITLE
How to cite relion4_tomo_robot?

### ISSUE THREAD

**Issue by GenevieveBuckley** [EuanPyle/autoTSAforRelion4#4]
Hi @alisterburt and @EuanPyle. My colleagues and I are working on a paper, and would like to cite relion4_tomo_robot. 

You don't currently have an easy way to do that. GitHub [suggests](https://citation-file-format.github.io/) to:
1. Create a DOI with [zenodo](https://zenodo.org/) (or similar), then
2. Add a [citation.cff file](https://citation-file-format.github.io/) with that info to your repository.

... step 3, ping me so we can attribute your work correctly in this academic article? Thanks for considering this!

**Comment by EuanPyle** [comment]
Thanks for citing us Genevieve! There isn't a paper specifically describing tomo_robot, although [this one](https://pubs.rsc.org/en/content/articlehtml/2022/fd/d2fd00022a) mentions it briefly in the supplementary. I suppose that probably isn't enough to cite that paper, so I will generate a DOI and .cff file now.

**Comment by EuanPyle** [comment]
All uploaded now, the .cff file is in the root of the package, thanks!

**Comment by GenevieveBuckley** [comment]
Thanks @EuanPyle!
